### ISSUE TITLE
Optionally Provide Customer for Marketplace 

### ISSUE THREAD

**Issue by agritheory** [agritheory/shipstation_integration#30]
In marketplace scenarios like Amazon, eBay, etc, allow a customer to be used (which will then be the receivable party) but set the `customer_name` field to be the ShipStation customer/name or id. The should be a Link field adjacent to Sales Partner in ShipStation Store.

**Comment by fproldan** [comment]
@agritheory this is solved in https://github.com/agritheory/shipstation_integration/pull/31 ?

**Comment by agritheory** [comment]
Yes
